### ISSUE TITLE
Coupling 0D solver with other codes (3D flow solvers, UQ, etc.)

### ISSUE THREAD

**Issue by menon-karthik** [SimVascular/svZeroDSolver#10]
I am working on an interface between this 0D and other solvers. For example, coupling with 3D flow solvers, where 0D solutions act as boundary conditions for the 3D flow solver. This is a continuation of the following issue before the C++ ZeroDSolver was moved to CBCL: https://github.com/SimVascular/svZeroDSolver/issues/71

Work so far: Dave added a framework for this interface in the old version of this C++ code (https://github.com/SimVascular/svZeroDSolver/issues/47#issuecomment-1201978268)

I am re-implementing this interface for this newer version of the code, along with required changes to the structure of the code (like have configreader return a pointer to a model). I will also be adding in more functionality as needed while I test interfacing it with svSolver and a parameter estimation code. 

Two specific things I foresee needing: (1) Pass parameters between the 0D solver and the external calling program; (2) Re-purpose flow and pressure BC blocks so they aren't just BCs for 0D vessels, but can also represent flow/pressure from an external solver when connected to other BC blocks (like closed-loop circulation).

**Comment by mrp089** [comment]
@menon-karthik I finally merged it (forgot about it over the holidays)! Can this be closed?

**Comment by mrp089** [comment]
Also, is there anything that needs to be merged on the 3D side (`svSolver`, `svFSI`)?

**Comment by menon-karthik** [comment]
The changes on the 3D cannot be merged yet because it hasn't been implemented and/or tested on all platforms. This issue can be closed though.
