### ISSUE TITLE
Output .csv file truncates time steps for a large (>93) vessel system

### ISSUE THREAD

**Issue by chlookaburra** [SimVascular/svZeroDSolver#105]
### Description

I am running a 116-vessel system with 1000 time steps and 10 cardiac cycles, and outputting the final cardiac cycle (`"output_all_cycles": false`).

The issue is that, starting with the 93th vessel, only 984 time steps are printed in the .csv file. Before that, 1000 time steps are printed.

[results_bug_length.csv](https://github.com/SimVascular/svZeroDSolver/files/14467396/results_bug_length.csv)

### Reproduction

[test0d_no_calib_refined.json](https://github.com/SimVascular/svZeroDSolver/files/14475115/test0d_no_calib_refined.json)

Create any >93 vessel system and set the following simulation parameters:

`"simulation_parameters": {
        "number_of_cardiac_cycles": 10,
        "number_of_time_pts_per_cardiac_cycle": 1000,
        "output_all_cycles": false
    },`

### Expected behavior

I was expecting to see a .csv file with 1000 time steps per vessel.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by menon-karthik** [comment]
@natalia-rubio Any chance this is related to #100?

**Comment by kharold23** [comment]
I ran the simulation with the attached json, and the output isn't truncated for me.  
[results.csv](https://github.com/SimVascular/svZeroDSolver/files/15476771/results.csv)

I'm using MacOS and the newest version of sv0D... What operating system did you run it on? (There have been system-specific issues before)

**Comment by chlookaburra** [comment]
I ran it on a MacOS when this issue was posted. I just checked again—and it works with the newest version of svZeroDSolver.
