### ISSUE TITLE
Drop in coverage 

### ISSUE THREAD

**Issue by menon-karthik** [SimVascular/svZeroDSolver#117]
### Description

Not sure if this is a bug, but the code coverage dropped almost 40% this week. I think it happened when #112 was merged. 

### Reproduction

This page in the codecov report says the coverage dropped in the last 7 days with the last PR: https://app.codecov.io/gh/SimVascular/svZeroDSolver?search=&trend=7%20days

### Expected behavior

The coverage report says routine functions like `create_junctions` are not being covered. This is not expected behavior. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by menon-karthik** [comment]
@ncdorn Do you mind looking into this to to try to figure out what changed with the coverage in the last pull request?

**Comment by ncdorn** [comment]
I think I found the cause of this. I believe the test cases must be run using execute_pysvzerod() as opposed to pysvzerod.simulate(). I have fixed this in my branch and am waiting to see if I get any coverage results

**Comment by mrp089** [comment]
Yeah, for coverage testing, we [call](https://github.com/SimVascular/svZeroDSolver/blob/ae38e9a888dac953d86c3d5f280f4f45d6fc775a/tests/utils.py#L34-L44) the `svzerod` executable via a Python `subprocess` (slow) as opposed to calling the Python interface (fast). This is, unfortunately, necessary to detect the execution with our coverage tool. The tests were still being executed, they just didn't show up in the coverage. It seems like @ncdorn figured out the fix already!

I noticed that the individual solver tests no longer appear when running `pytest` but only `test_solver.py::test_all PASSED`. This is not a big deal, but it could be nice to show which individual tests are being executed. Maybe there's a way to do that with a pytest fixture ([example here](https://github.com/SimVascular/svFSIplus/blob/b92add4a33eea4b6632fb323f484f08d3e62a716/tests/test_heats.py#L15-L19)) by pulling out `testfiles` from `test_all`?

**Comment by ncdorn** [comment]
@mrp089 Thanks for the input. I will implement the pytest fixture to show which individual tests are being executed. On the topic of codecov, what is the best way to generate a coverage report for my individual branch? I would like to do this before I submit the pull request.

**Comment by mrp089** [comment]
Good idea! You can follow [these steps](https://github.com/SimVascular/svZeroDSolver/blob/ae38e9a888dac953d86c3d5f280f4f45d6fc775a/.github/workflows/test.yml#L47-L56) locally on your machine (which executes [this code](https://github.com/SimVascular/svZeroDSolver/blob/ae38e9a888dac953d86c3d5f280f4f45d6fc775a/CMakeLists.txt#L53-L56)).

**Comment by mrp089** [comment]
If it doesn't work immediately (which it didn't on my Mac), you can also open a pull request (set it to draft). Then, the pipeline will run for each commit, and you'll be able to download the coverage report under the Annotations of each [pipeline](https://github.com/SimVascular/svZeroDSolver/actions/runs/9899433142).
