### ISSUE TITLE
svZeroDGUI for 0d Model Generation

### ISSUE THREAD

**Issue by emilinmathew** [SimVascular/svZeroDSolver#121]
### Use Case

The svZeroDGUI web application allows users to generate input files for the svZeroDSolver by drawing the network on an easy-to-use GUI. This provides an alternative to manually creating files and is useful for users without access to a 3D model.

### Problem

Currently, there are two primary methods for creating 0D input files in SimVascular. The first method involves extracting the 0D model from an existing 3D model. This approach has significant drawbacks, including the requirement for a 3D model, which may not always be available. Additionally, this method is computationally expensive and time-intensive, which can be a barrier for many users.

The second method is manually creating the 0D input files, which is needed when a 3D model is not available or when a stand-alone simulation is desired. The lack of automation means that repetitive tasks must be done manually, which is inefficient and prone to errors. Furthermore, manually created files are difficult to debug and this approach lacks scalability, making it cumbersome to handle larger or more complex networks.

Given that 0D simulations are designed to be fast and efficient, these current methods do not fully align with these goals. An improved solution is needed to streamline the creation of 0D models, enhancing speed, efficiency, and scalability.

### Solution

The svZeroDGUI application addresses these needs by providing an intuitive graphical user interface for drawing the network and generating the input files. This solution:
- **Eliminates the Need for a 3D Model:** Allows users to create models without relying on an existing 3D model.
- **Automates File Generation:** Simplifies and speeds up the process of creating input files.
- **Enhances Scalability:** Facilitates the creation of larger and more complex networks efficiently.

The web application's frontend is built with HTML, CSS, and JavaScript, utilizing Cytoscape.js for network visualization and manipulation. The frontend features an intuitive node-linking system, where users can click on a node and drag an edge to connect it, making network construction straightforward. It also includes interactive parameter settings, enabling users to input vessel information, select junction types, and configure various network parameters directly within the application.

On the backend, Node.js handles server-side logic, while Cypress is employed for automated end-to-end testing to ensure the application functions correctly. The application incorporates an integrated validation framework that automatically checks the network for errors, such as missing elements or incorrect configurations, and provides error messages to assist users in correcting these issues. This setup ensures a user-friendly experience for building and editing 0D models while maintaining robust functionality and reliability.

https://github.com/user-attachments/assets/94dba682-8434-4d11-9932-576576279c2d

### Alternatives considered

We considered an alternative method for generating input files by training a computer vision model to parse hand-drawn circuit diagrams. Although this approach was effective for smaller inputs, we found that a GUI is more intuitive and user-friendly. The GUI not only simplifies the process of creating and editing the network structure but also facilitates the input of parameters directly into the files, rather than just generating the JSON structure. This makes it easier for users to manage and configure their models, improving the overall user experience.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by mrp089** [comment]
Amazing work! We have wanted something like that for at least four years, and you did it!
