### ISSUE TITLE
Output CSV requires vessels to be named "branch*"

### ISSUE THREAD

**Issue by JohnDLee** [SimVascular/svZeroDSolver#16]
To have an output for a particular vessel show up in the C++ version, the vessels must have the name ```branch*```.

For example, below, the vessel called branch_mpa shows up, but the vessel lpa_tree does not. This error occurs regardless of any options used (here I use output_mean_only and output_last_cycle_only for clarity). 
<img width="387" alt="Screen Shot 2022-11-01 at 9 53 46 PM" src="https://user-images.githubusercontent.com/26451348/199376097-23dee3be-6a8d-42d7-83ea-baa77b7e2da6.png">
<img width="222" alt="Screen Shot 2022-11-01 at 9 54 00 PM" src="https://user-images.githubusercontent.com/26451348/199376132-e9216211-7cdd-424c-b9a9-d3292b2ba2b7.png">

**Comment by menon-karthik** [comment]
This was resolved in #31. Closing.
