### ISSUE TITLE
Add CMake commands for building installer

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/svZeroDSolver#50]
There are currently no CMake commands to build an installer for the `svzerodsolver` and `svzerodcalibrator` executables. 

I will add CMake CPack commands to build the installers.

**Comment by mrp089** [comment]
You can add [these lines](https://github.com/SimVascular/SimVascular/blob/edd1fc7c26cf9550594a7362d66bb5d0fadda4d9/.github/workflows/build.yml#L82-L89) from the SimVascular repository to include uploading the executables in GitHub actions.

**Comment by ktbolt** [comment]
Modify the `svZeroDSolver/distribution/CMakeLists.txt` code to install into `/usr/local/sv/svZeroDSolver` rather than `/usr/local/sv/ZeroDSolver`
